version: "3"
services:
  devportal:
    image: ashrujitpal/devportal:1.0.0
    ports:
      - "8080:8080"
    networks:
      - devportal-network

  database:
    image: mysql:8.0.19
    networks:
      - devportal-network
    environment:
      - MYSQL_DATABASE=devportal
      - MYSQL_ROOT_PASSWORD=password

networks:
  devportal-network:
    driver: bridge
