insert into sub_api_tbl (parent_api_name, api_name, api_descripton, swagger_name, api_image_url, api_page_url, api_devportal_link) VALUES ( 'Open Bank', 'Current Account', 'It orchestrates a consumer checking/demand deposit account', 'current-account.yaml', '/images/cards/img02.jpeg', '/fabapis/apidetails', 'https://sb-fabincubationapigmailcom-dev.developer.eu.apiconnect.ibmcloud.com/node/197');

insert into sub_api_tbl (parent_api_name, api_name, api_descripton, swagger_name, api_image_url, api_page_url, api_devportal_link) VALUES ( 'Open Bank', 'Savings Account', 'This service domain orchestrates a consumer savings account', 'savings-account.json', '/images/cards/img08.jpeg', '/fabapis/apidetails', 'https://sb-fabincubationapigmailcom-dev.developer.eu.apiconnect.ibmcloud.com/node/279');
insert into sub_api_tbl (parent_api_name, api_name, api_descripton, swagger_name, api_image_url, api_page_url, api_devportal_link) VALUES ( 'Open Bank', 'Remittance', 'This service domain provides a customer payment service', 'remittance.json', '/images/cards/img06.jpeg', '/fabapis/apidetails', 'https://sb-fabincubationapigmailcom-dev.developer.eu.apiconnect.ibmcloud.com/node/273');

insert into sub_api_tbl (parent_api_name, api_name, api_descripton, swagger_name, api_image_url, api_page_url, api_devportal_link) VALUES ( 'Open Bank', 'Customer Position', 'Maintains a consolidated financial position for a customer combining all products & services in use', 'customer-position.json', '/images/cards/img04.jpeg', '/fabapis/apidetails', 'https://sb-fabincubationapigmailcom-dev.developer.eu.apiconnect.ibmcloud.com/node/138');
insert into sub_api_tbl (parent_api_name, api_name, api_descripton, swagger_name, api_image_url, api_page_url, api_devportal_link) VALUES ( 'Open Bank', 'Customer Product Service Eligibility', 'This service domain handles profile of Customer eligible Product Service  ', 'customer-product-service-eligibility.json', '/images/cards/img05.jpeg', '/fabapis/apidetails', 'https://sb-fabincubationapigmailcom-dev.developer.eu.apiconnect.ibmcloud.com/node/225');
--insert into sub_api_tbl (parent_api_name, api_name, api_descripton, swagger_name, api_image_url, api_page_url, api_devportal_link) VALUES ( 'Open Bank', 'Customer Profile', 'Is used to tune the customer experience during any real time interaction with the bank', 'customer-profile.json', '/images/cards/img06.jpeg', '/fabapis/apidetails', 'https://sb-fabincubationapigmailcom-dev.developer.eu.apiconnect.ibmcloud.com/node/227’);
insert into sub_api_tbl (parent_api_name, api_name, api_descripton, swagger_name, api_image_url, api_page_url, api_devportal_link) VALUES ( 'Open Bank', 'Customer Profile', 'Is used to tune the customer experience during any real time interaction with the bank', 'customer-profile.json', '/images/cards/img06.jpeg', '/fabapis/apidetails', 'https://sb-fabincubationapigmailcom-dev.developer.eu.apiconnect.ibmcloud.com/node/227');
insert into sub_api_tbl (parent_api_name, api_name, api_descripton, swagger_name, api_image_url, api_page_url, api_devportal_link) VALUES ( 'Open Bank', 'Customer Credit Rating', 'This service domain maintains and administers the banks credit assessment for customers', 'customer-credit-rating.json', '/images/cards/img01.jpeg', '/fabapis/apidetails', 'https://sb-fabincubationapigmailcom-dev.developer.eu.apiconnect.ibmcloud.com/node/215');
insert into sub_api_tbl (parent_api_name, api_name, api_descripton, swagger_name, api_image_url, api_page_url, api_devportal_link) VALUES ( 'Open Bank', 'Customer Behavior Insights', 'Handles the design and maintenance of a portfolio of customer behavior models', 'customer-behavior-insights.json', '/images/cards/img05.jpeg', '/fabapis/apidetails', 'https://sb-fabincubationapigmailcom-dev.developer.eu.apiconnect.ibmcloud.com/node/205');
insert into sub_api_tbl (parent_api_name, api_name, api_descripton, swagger_name, api_image_url, api_page_url, api_devportal_link) VALUES ( 'Open Bank', 'Customer Offer', 'This service domain orchestrates the processing of a product offer for a new/established customer', 'customer-offer.json', '/images/cards/img03.jpeg', '/fabapis/apidetails', 'https://sb-fabincubationapigmailcom-dev.developer.eu.apiconnect.ibmcloud.com/node/221');
insert into sub_api_tbl (parent_api_name, api_name, api_descripton, swagger_name, api_image_url, api_page_url, api_devportal_link) VALUES ( 'Open Bank', 'Customer Relationship Management', 'This service domain develops, executes a customer plan to maintain and build a customer relationship', 'customer-relationship-management.json', '/images/cards/img08.jpeg', '/fabapis/apidetails', 'https://sb-fabincubationapigmailcom-dev.developer.eu.apiconnect.ibmcloud.com/node/233');
insert into sub_api_tbl (parent_api_name, api_name, api_descripton, swagger_name, api_image_url, api_page_url, api_devportal_link) VALUES ( 'Open Bank', 'Consumer Loan', 'This service domain handles the fulfillment of a consumer loan product', 'consumer-loan.json', '/images/cards/img01.jpeg', '/fabapis/apidetails', 'https://sb-fabincubationapigmailcom-dev.developer.eu.apiconnect.ibmcloud.com/node/175');
insert into sub_api_tbl (parent_api_name, api_name, api_descripton, swagger_name, api_image_url, api_page_url, api_devportal_link) VALUES ( 'Open Bank', 'Underwriting', 'This service domain manages the underwriting decision process for loan origination.', 'underwriting.json', '/images/cards/img05.jpeg', '/fabapis/apidetails', 'https://sb-fabincubationapigmailcom-dev.developer.eu.apiconnect.ibmcloud.com/node/293');
insert into sub_api_tbl (parent_api_name, api_name, api_descripton, swagger_name, api_image_url, api_page_url, api_devportal_link) VALUES ( 'Open Bank', 'Deposit Account', 'This service domain handles the set-up and fulfillment of consumer fixed term deposits', 'deposit-account.json', '/images/cards/img03.jpeg', '/fabapis/apidetails', 'https://sb-fabincubationapigmailcom-dev.developer.eu.apiconnect.ibmcloud.com/node/243');
insert into sub_api_tbl (parent_api_name, api_name, api_descripton, swagger_name, api_image_url, api_page_url, api_devportal_link) VALUES ( 'Open Bank', 'Payment Execution', 'Processes the movement of funds between accounts within the bank or to/from an another account', 'payment-execution.json', '/images/cards/img05.jpeg', '/fabapis/apidetails', 'https://sb-fabincubationapigmailcom-dev.developer.eu.apiconnect.ibmcloud.com/node/247');
insert into sub_api_tbl (parent_api_name, api_name, api_descripton, swagger_name, api_image_url, api_page_url, api_devportal_link) VALUES ( 'Open Bank', 'Payment Order', 'Handles the bank-side processing of funds transfers', 'payment-order.json', '/images/cards/img06.jpeg', '/fabapis/apidetails', 'https://sb-fabincubationapigmailcom-dev.developer.eu.apiconnect.ibmcloud.com/node/251');
insert into sub_api_tbl (parent_api_name, api_name, api_descripton, swagger_name, api_image_url, api_page_url, api_devportal_link) VALUES ( 'Open Bank', 'Credit Charge Card', 'Orchestrates the scheduled maintenance and transactional activities', 'credit-charge-card.json', '/images/cards/img08.jpeg', '/fabapis/apidetails', 'https://sb-fabincubationapigmailcom-dev.developer.eu.apiconnect.ibmcloud.com/node/193');
insert into sub_api_tbl (parent_api_name, api_name, api_descripton, swagger_name, api_image_url, api_page_url, api_devportal_link) VALUES ( 'Open Bank', 'Correspondent Bank Data Management', 'This service domain maintains correspondent bank reference details.', 'correspondent-bank-data-management.json', '/images/cards/img06.jpeg', '/fabapis/apidetails', 'https://sb-fabincubationapigmailcom-dev.developer.eu.apiconnect.ibmcloud.com/node/191');
insert into sub_api_tbl (parent_api_name, api_name, api_descripton, swagger_name, api_image_url, api_page_url, api_devportal_link) VALUES ( 'Open Bank', 'Correspondent Bank', 'This domain fulfills arrangements between the bank and the correspondent banking partners.', 'correspondent-bank.json', '/images/cards/img07.jpeg', '/fabapis/apidetails', 'https://sb-fabincubationapigmailcom-dev.developer.eu.apiconnect.ibmcloud.com/node/189');
insert into sub_api_tbl (parent_api_name, api_name, api_descripton, swagger_name, api_image_url, api_page_url, api_devportal_link) VALUES ( 'Open Bank', 'Ach Fulfillment', 'Operates the Automated Clearing House access gateway between bank and ACH service provider', 'ach-fulfillment.json', '/images/cards/img02.jpeg', '/fabapis/apidetails', 'https://sb-fabincubationapigmailcom-dev.developer.eu.apiconnect.ibmcloud.com/node/119');
insert into sub_api_tbl (parent_api_name, api_name, api_descripton, swagger_name, api_image_url, api_page_url, api_devportal_link) VALUES ( 'Open Bank', 'Card Delinquent Account Handling', 'This handles delinquent accounts for follow-up of payments due through periodic review and contacts', 'card-delinquent-account-handling.json', '/images/cards/img08.jpeg', '/fabapis/apidetails', 'https://sb-fabincubationapigmailcom-dev.developer.eu.apiconnect.ibmcloud.com/node/129');

insert into sub_api_tbl (parent_api_name, api_name, api_descripton, swagger_name, api_image_url, api_page_url, api_devportal_link) VALUES ( 'Open Bank', 'Card Ecommerce Gateway', 'Orchestrates the processing of e-commerce transactions for authentication, authorization, etc', 'card-ecommerce-gateway.json', '/images/cards/img01.jpeg', '/fabapis/apidetails', 'https://sb-fabincubationapigmailcom-dev.developer.eu.apiconnect.ibmcloud.com/node/131');
insert into sub_api_tbl (parent_api_name, api_name, api_descripton, swagger_name, api_image_url, api_page_url, api_devportal_link) VALUES ( 'Open Bank', 'Card Financial Settlement', 'This orchestrates the settlement of transactions between Issuers and Acquirers through Card Network', 'card-financial-settlement.json', '/images/cards/img02.jpeg', '/fabapis/apidetails', 'https://sb-fabincubationapigmailcom-dev.developer.eu.apiconnect.ibmcloud.com/node/133');
insert into sub_api_tbl (parent_api_name, api_name, api_descripton, swagger_name, api_image_url, api_page_url, api_devportal_link) VALUES ( 'Open Bank', 'Card Authorization', 'Responsible for the real time card authorization decisions for credit/charge cards', 'card-authorization.json', '/images/cards/img04.jpeg', '/fabapis/apidetails', 'https://sb-fabincubationapigmailcom-dev.developer.eu.apiconnect.ibmcloud.com/node/121');
insert into sub_api_tbl (parent_api_name, api_name, api_descripton, swagger_name, api_image_url, api_page_url, api_devportal_link) VALUES ( 'Open Bank', 'Card Case', 'This service domain handles the processing of a customer case typically a disputed card', 'card-case.json', '/images/cards/img05.jpeg', '/fabapis/apidetails', 'https://sb-fabincubationapigmailcom-dev.developer.eu.apiconnect.ibmcloud.com/node/123');
insert into sub_api_tbl (parent_api_name, api_name, api_descripton, swagger_name, api_image_url, api_page_url, api_devportal_link) VALUES ( 'Open Bank', 'Card Clearing', 'This service domain captures and consolidation of card financial transactions', 'card-clearing.json', '/images/cards/img06.jpeg', '/fabapis/apidetails', 'https://sb-fabincubationapigmailcom-dev.developer.eu.apiconnect.ibmcloud.com/node/125');
insert into sub_api_tbl (parent_api_name, api_name, api_descripton, swagger_name, api_image_url, api_page_url, api_devportal_link) VALUES ( 'Open Bank', 'Card Collections', 'This administers the recovery of outstanding amounts from cancelled card accounts', 'card-collections.json', '/images/cards/img07.jpeg', '/fabapis/apidetails', 'https://sb-fabincubationapigmailcom-dev.developer.eu.apiconnect.ibmcloud.com/node/127');
insert into sub_api_tbl (parent_api_name, api_name, api_descripton, swagger_name, api_image_url, api_page_url, api_devportal_link) VALUES ( 'Open Bank', 'Account Recovery', 'This service domain handles the restructuring of a distressed account (loan) after standard recovery', 'account-recovery.json', '/images/cards/img01.jpeg', '/fabapis/apidetails', 'https://sb-fabincubationapigmailcom-dev.developer.eu.apiconnect.ibmcloud.com/node/113');
insert into sub_api_tbl (parent_api_name, api_name, api_descripton, swagger_name, api_image_url, api_page_url, api_devportal_link) VALUES ( 'Open Bank', 'Transaction Authorization', 'Handles risk based authorization for interactive customer transactions', 'transaction-authorization.json', '/images/cards/img04.jpeg', '/fabapis/apidetails', 'https://sb-fabincubationapigmailcom-dev.developer.eu.apiconnect.ibmcloud.com/node/291');
insert into sub_api_tbl (parent_api_name, api_name, api_descripton, swagger_name, api_image_url, api_page_url, api_devportal_link) VALUES ( 'Open Bank', 'Regulatory Compliance', 'Provides a service to interpret regulatory compliance requirements', 'regulatory-compliance.json', '/images/cards/img04.jpeg', '/fabapis/apidetails', 'https://sb-fabincubationapigmailcom-dev.developer.eu.apiconnect.ibmcloud.com/node/267');
insert into sub_api_tbl (parent_api_name, api_name, api_descripton, swagger_name, api_image_url, api_page_url, api_devportal_link) VALUES ( 'Open Bank', 'Regulatory Reporting', 'This service domain administers required tasks to meet banks regulatory reporting obligations.', 'regulatory-reporting.json', '/images/cards/img05.jpeg', '/fabapis/apidetails', 'https://sb-fabincubationapigmailcom-dev.developer.eu.apiconnect.ibmcloud.com/node/271');

insert into api_desc_tbl (parent_api_name, api_name, api_description, swagger_name, api_devportal_link, api_version, api_owner, api_status, key_feature, key_feature1, key_feature2, key_feature3 , key_feature4) VALUES 
( 'Open Bank', 'Current Account', 'This service domain orchestrates a consumer checking/demand deposit account. The typical range of services and fees covers payments and deposits, standing orders, sweeps, liens, check and debit card access', 'current-account.yaml', 'https://sb-fabincubationapigmailcom-dev.developer.eu.apiconnect.ibmcloud.com/node/197', 'v1', 'FAB', 'Published', 'Issue cards','check-books for an account','Process deposits and withdrawals' ,'Handle standing orders and direct debits' , 'Provide balance/statements and reports');
