apiVersion: apps/v1
kind: Deployment
metadata:
  name: devportal-webapp
spec:
  selector:
    matchLabels:
      app: devportal-webapp
  replicas: 1
  template:
    metadata:
      labels:
        app: devportal-webapp
    spec:
      containers:
        - name: devportal-webapp
          image: ashrujitpal/k8s-devportal:latest
