apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysqldb
  replicas: 1
  template:
    metadata:
      labels: 
        app: mysqldb
    spec:
      containers:
      - name: mysqldb
        image: mysql:8.0.19
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: password
          - name: MYSQL_USER
            value: userabc
          - name: MYSQL_PASSWORD
            value: password
          - name: MYSQL_DATABASE
            value: devportal      
        volumeMounts:
          - name: mysql-persistent-storage
            mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pvc            

---

apiVersion: v1
kind: Service
metadata:
  name: devportal-mysqldb
spec:
  selector:
    app: mysqldb
  ports:
    - name: mysqldb
      port: 3306
      port: 33060
  type: ClusterIP 
  